default:
  image: python:3.8
  tags:
    - research

stages:
  - linting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

test:
  stage: test
  needs: []
  script:
    - pip install .
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
