default:
  image: python:3.8
  tags:
    - research

stages:
  - linting
  - test

flake8:
  stage: linting
  script:
  - python -m pip install flake8
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics    
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

test:
  stage: test
  services:
  - chansoosong/oagdedupe-postgres
  variables:
    POSTGRES_DB: db
    POSTGRES_USER: username
    POSTGRES_PASSWORD: password
    PGDATA: /var/lib/pgsql/data/pgdata
  needs: []
  script:
  - export DATABASE_URL=postgresql+psycopg2://username:password@0.0.0.0:5432/db
  - python -m pip install .
  - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: pytest.xml
