default:
  image: python:3.8
  tags:
    - research

stages:
  - test

test:
  stage: test
  needs: []
  script:
    - pip install .
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
