@startuml Class Hierarchy


'---------------------Abstract Nodes------------------------------'

abstract class BaseModel

'database'
database db [
    db
]

'---------------------Edges------------------------------'

'api'
' BaseModel <|-- "ext" Dedupe
' BaseModel <|-- "ext" RecordLinkage
' BaseModel <|-- "ext" Fapi

node "Domain Layer" {
    'blocking'
    abstract class BaseOptimizer

    'clustering'
    abstract class BaseCluster

    BaseModel *-- Blocking
    BaseModel *-- BaseCluster

    'blocking
    Blocking *-- Forward
    Blocking *-- Pairs
    Blocking *-- Conjunctions

    Conjunctions *-- BaseOptimizer
}

'repository
node Repository {
    abstract class BaseRepository
    abstract class BaseRepositoryBlocking
    Forward *-- BaseRepositoryBlocking
    Pairs *-- BaseRepositoryBlocking
    BaseOptimizer *-- BaseRepositoryBlocking
    BaseCluster *-- BaseRepository
    BaseModel *-- BaseRepository
    BaseRepository *-- BaseRepositoryBlocking
}

Repository --> db

@enduml
