@startuml Class Hierarchy

'---------------------Abstract Nodes------------------------------'

abstract class BaseModel

'compute'
abstract class BaseRepository
abstract class BaseRepositoryBlocking

'blocking'
abstract class BaseBlocking
abstract class BaseForward
abstract class BaseConjunctions
abstract class BasePairs
abstract class BaseOptimizer

'clustering'
abstract class BaseCluster

'---------------------Edges------------------------------'

'api'
BaseModel <|-- "ext" Dedupe
BaseModel <|-- "ext" RecordLinkage
BaseModel <|-- "ext" Fapi
BaseModel *-- BaseRepository
BaseModel *-- BaseRepositoryBlocking
BaseModel *-- BaseBlocking
BaseModel *-- BaseCluster

'blocking
BaseBlocking *-- BaseForward
BaseBlocking *-- BasePairs
BaseBlocking *-- BaseConjunctions

BaseConjunctions *-- BaseOptimizer
BaseOptimizer <|-- "ext" DynamicProgram

BaseForward <|-- BlockSchemes
BaseConjunctions <|-- BlockSchemes
BaseOptimizer <|-- BlockSchemes

'clustering
BaseCluster <|-- "ext" ConnectedComponents

'compute
BaseRepository *-- BaseRepositoryBlocking
BaseForward *-- BaseRepositoryBlocking
BasePairs *-- BaseRepositoryBlocking
BaseConjunctions *-- BaseRepositoryBlocking
BaseOptimizer *-- BaseRepositoryBlocking
BaseCluster *-- BaseRepository

@enduml
